[package]
name = "squid"
version = "0.3.0"
description = "An AI-powered command-line tool for code reviews and suggestions."
authors = ["Denys Vuika <denys.vuika@gmail.com>"]
license = "Apache-2.0"
edition = "2024"

[dependencies]
async-openai = { version = "0.32", features = ["chat-completion"] }
clap = { version = "4.5", features = ["derive"] }
console = "0.15"
dotenvy = "0.15.7"
env_logger = "0.11.8"
futures = "0.3"
inquire = "0.9"
log = "0.4.29"
regex = "1.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.0", features = ["full"] }
walkdir = "2.5"
